name:                aoc17-hs
version:             0.1.0.0
github:              "githubuser/aoc17-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/aoc17-hs#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 6.3.0 && < 7
- criterion
- primitive
- containers
- vector
- matrices
- split

library:
  source-dirs: lib

executables:
  task1-exe:
    main:                Main.hs
    source-dirs:         task1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task2-exe:
    main:                Main.hs
    source-dirs:         task2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task3-exe:
    main:                Main.hs
    source-dirs:         task3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task4-exe:
    main:                Main.hs
    source-dirs:         task4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task5-exe:
    main:                Main.hs
    source-dirs:         task5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task6-exe:
    main:                Main.hs
    source-dirs:         task6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task7-exe:
    main:                Main.hs
    source-dirs:         task7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task8-exe:
    main:                Main.hs
    source-dirs:         task8
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task9-exe:
    main:                Main.hs
    source-dirs:         task9
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task10-exe:
    main:                Main.hs
    source-dirs:         task10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task11-exe:
    main:                Main.hs
    source-dirs:         task11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task12-exe:
    main:                Main.hs
    source-dirs:         task12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task13-exe:
    main:                Main.hs
    source-dirs:         task13
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task14-exe:
    main:                Main.hs
    source-dirs:         task14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task15-exe:
    main:                Main.hs
    source-dirs:         task15
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task16-exe:
    main:                Main.hs
    source-dirs:         task16
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task17-exe:
    main:                Main.hs
    source-dirs:         task17
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task18-exe:
    main:                Main.hs
    source-dirs:         task18
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task19-exe:
    main:                Main.hs
    source-dirs:         task19
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs

  task20-exe:
    main:                Main.hs
    source-dirs:         task20
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc17-hs